#!/bin/bash


# Terminate already running bar instances
killall -q waybar

# Wait until the processes have been shut down
while pgrep -x waybar >/dev/null; do sleep 1; done

if [[ ! $(pidof waybar) ]]; then
	waybar 
fi
